aux_source_directory(. yolov11_pose)
#set(OpenCV_DIR ${CMAKE_SOURCE_DIR}/../libs/opencv-mobile-4.5.4-android/sdk/native/jni)
find_package(OpenCV REQUIRED core imgproc highgui)
find_package(ncnn REQUIRED)
add_library(yolov11_pose_lib yolov11_pose_with_post_process.cpp)
target_link_libraries(yolov11_pose_lib ${OpenCV_LIBS})
target_link_libraries(yolov11_pose_lib ncnn)
